"""jdsl — behavior-tree agents with DSPy-style signatures, run by a tree-walking
interpreter. Authoring surface: tool, root, seq, sel, repeat, act, check, predict, ref, store."""

from jdsl.context import Blackboard, ContextWindow, ModelTurn, Ref, RunContext, ToolCall, Write
from jdsl.dsl import (
    act,
    check,
    guard,
    guard_call,
    invert,
    oneshot,
    optional,
    predict,
    react,
    ref,
    repeat,
    root,
    sel,
    seq,
    store,
    timeout,
    tool,
)
from jdsl.provider import LanguageModel
from jdsl.render import render
from jdsl.trace import (
    BlobStore,
    EventKind,
    EventSource,
    JsonlTraceSink,
    ListTraceSink,
    NullTraceSink,
    Redactor,
    SafeSink,
    TraceEvent,
    read_events,
    segment_episodes,
)
from jdsl.tree import (
    Action,
    Check,
    Decorator,
    Guard,
    GuardCall,
    Invert,
    Node,
    OneShot,
    Optional,
    Predict,
    React,
    Repeat,
    Root,
    Selector,
    Sequence,
    Status,
    Timeout,
    assign_runtime_ids,
)

__all__ = [
    "tool",
    "act",
    "seq",
    "sel",
    "repeat",
    "check",
    "guard",
    "guard_call",
    "predict",
    "react",
    "invert",
    "optional",
    "timeout",
    "oneshot",
    "root",
    "store",
    "ref",
    "render",
    "Ref",
    "Status",
    "Node",
    "Action",
    "Check",
    "Guard",
    "GuardCall",
    "Repeat",
    "Sequence",
    "Selector",
    "Predict",
    "React",
    "Decorator",
    "Invert",
    "Optional",
    "Timeout",
    "OneShot",
    "Root",
    "LanguageModel",
    "RunContext",
    "Blackboard",
    "ContextWindow",
    "ToolCall",
    "ModelTurn",
    "Write",
    "assign_runtime_ids",
    "TraceEvent",
    "EventKind",
    "EventSource",
    "NullTraceSink",
    "ListTraceSink",
    "JsonlTraceSink",
    "SafeSink",
    "BlobStore",
    "Redactor",
    "read_events",
    "segment_episodes",
]
